site_name: Test docs
site_description: 'A docs test'
site_author: 'Michael Hausenblas'
docs_dir: docs/
repo_name: 'mhausenblas/mkdocs-template'
repo_url: 'https://github.com/mhausenblas/mkdocs-template'
nav:
    - Home: index.md
    - Proyectos: 
      - RBCAR AI2: 
        - rbcar/index.md
        - Batería: rbcar/bateria.md
theme:
  name: 'material'
