site_name: Sistemas y Róbotica
site_description: 'Web personal para la difusión de contenido diverso de sistemas y robótica'
site_author: 'Rafael Carbonell Lázaro'
docs_dir: docs/
repo_name: 'racarla96/racarla96.github.io'
repo_url: 'https://github.com/racarla96/racarla96.github.io'
nav:
    - Home: index.md
    - Proyectos: 
      - RBCAR AI2: 
        - rbcar/index.md
        - Batería: rbcar/bateria.md
theme:
  name: 'material'
