site_name: Sistemas y Róbotica
site_description: 'Web personal para la difusión de contenido diverso de sistemas y robótica'
site_author: 'Rafael Carbonell Lázaro'
docs_dir: docs/
repo_name: 'racarla96/racarla96.github.io'
repo_url: 'https://github.com/racarla96/racarla96.github.io'
nav:
    - Home: index.md
    - Proyectos: 
      - Caddy AI2: 
        - caddy_ai2/index.md
        - Batería: caddy_ai2/bateria.md
        - Gamepad: caddy_ai2/gamepad.md
    - Sensores:
      - sensores/index.md
      - Posicionamiento en interiores:
        - sensores/pos_int/index.md
        - Marvelmind: sensores/pos_int/mavermind.md
    - Comunicaciones:
      - comunicacion/index.md
      - UART: comunicacion/uart.md
    - Prototipos:
      - prototipos/index.md
      - LEGO: prototipos/lego/index.md
      - Quanser: prototipos/quanser/index.md
    - Material Educativo:
      - material_educativo/index.md
theme:
  name: 'material'
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences